### ISSUE TITLE
Transition method should document throwable exceptions

### ISSUE THREAD

**Issue by mecha** [RebelCode/booking-transitioner-interface#2]
The [`transition()`] method does not document that it can throw [`TransitionerExceptionInterface`] and [`CouldNotTransitionExceptionInterface`].

[`transition()`]: https://github.com/RebelCode/booking-transitioner-interface/blob/develop/src/TransitionerInterface.php#L26

[`TransitionerExceptionInterface`]: https://github.com/RebelCode/booking-transitioner-interface/blob/develop/src/Exception/CouldNotTransitionExceptionInterface.php

[`CouldNotTransitionExceptionInterface`]: https://github.com/RebelCode/booking-transitioner-interface/blob/develop/src/Exception/TransitionerExceptionInterface.php

**Comment by XedinUnknown** [comment]
Done.
